### ISSUE TITLE
最新版功能设置里面的翻译能同步一下老版本吗

### ISSUE THREAD

**Issue by fgr178707** [dingzhen-vape/WurstCN#11]
老版本没有
下方截图版本是1.20.1
![image](https://github.com/dingzhen-vape/WurstCN/assets/109357981/f111afd2-5a7e-4580-a5f5-7c2e71ad4f60)

1.18就没有设置页面翻译

左侧1.18，右侧1.20.1
![image](https://github.com/dingzhen-vape/WurstCN/assets/109357981/de8b3b11-9aa9-4017-a3d1-4c0d768d7d37)

**Comment by dingzhen-vape** [comment]
好

**Comment by fgr178707** [comment]
> 好

麻烦了

**Comment by dingzhen-vape** [comment]
重新上传了

**Comment by dingzhen-vape** [comment]
老版本的结构与新版本的结构不太一样,耗时有点多,所以(包容一下)就这样吧

**Comment by fgr178707** [comment]
> 重新上传了

好的

**Comment by fgr178707** [comment]
> 老版本的结构与新版本的结构不太一样,耗时有点多,所以(包容一下)就这样吧

理解
