### ISSUE TITLE
.XXX 介绍翻译

### ISSUE THREAD

**Issue by fgr178707** [dingzhen-vape/WurstCN#14]
我问一下这个能做翻译吗
![image](https://github.com/dingzhen-vape/WurstCN/assets/109357981/44c50d25-ae4e-4438-b5a8-d8a3bcb155c1)

**Comment by buiawpkgew1** [comment]
能翻译

**Comment by dingzhen-vape** [comment]
暂时不会进行指令功能的翻译,请谅解
