### ISSUE TITLE
功能设置里面的能翻译一下吗

### ISSUE THREAD

**Issue by fgr178707** [dingzhen-vape/WurstCN#19]
之前版本 https://github.com/dingzhen-vape/WurstCN/issues/11
最新版本1.20.5:"
![image](https://github.com/dingzhen-vape/WurstCN/assets/109357981/3b91740c-80f3-4b8c-8061-cea36dc542d5)

**Comment by dingzhen-vape** [comment]
修复了一个bug出现了更多的bug，现在过滤器已经汉化好了，有些功能的功能失去了汉化
