### ISSUE TITLE
Wurst-ClientCN-v7.43-MC1.21 闪退

### ISSUE THREAD

**Issue by fgr178707** [dingzhen-vape/WurstCN#21]
[日志.txt](https://github.com/user-attachments/files/16215334/default.txt)

![image](https://github.com/user-attachments/assets/d018e7c9-acbc-4a4e-8973-556023c06317)

**Comment by dingzhen-vape** [comment]
Wurst开发者已经更新7.44，已经跟进汉化，检查是否还会出现此问题
